import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:email_validator/email_validator.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:intl/intl.dart';
import 'package:pdm_app/models/models.dart';
import 'package:pdm_app/services/services.dart';
import 'package:pdm_app/shared/shared.dart';
import 'package:pdm_app/ui/widgets/widgets.dart';

part 'splash.dart';
part 'login.dart';
part 'signup.dart';
part 'home.dart';
part 'profile.dart';
part '../projects/create.dart';
